import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
import { useRouter } from "next/router";
import { useEffect } from "react";
import {useMetamask,useAddress} from '@thirdweb-dev/react'

export default function Home() {
  const connectWithMetamask=useMetamask();
  const address=useAddress();
  const router=useRouter();

  useEffect(()=>{},[address])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header/>
         <section className="container content-section">
          <h1 className="section-header"></h1>
          <h2 className="section-header">Featured Artist: Betty Blockchain</h2>
          <hr />

          <div className="shop-items">
            <div className="shop-item">
              <span className="shop-item-title">Better Out, Then In</span>
              <img
                className="shop-item-image"
                src="./images/323161673_1378759992964884_8373740681875230611_n%20(1).jpg"
              />
              <div className="shop-item-details">
                <span className="shop-item-price">Private</span>
                <button className="btn btn-primary shop-item-button" type="button">
                  ADD TO CART
                </button>
              </div>
            </div>
            <div className="shop-item">
              <span className="shop-item-title">Crystal Lake Carnage</span>
              <img
                className="shop-item-image"
                src="./images/323372818_538516134996848_8300558409947033744_n%20(1).jpg"
              />
              <div className="shop-item-details">
                <span className="shop-item-price">Private</span>
                <button className="btn btn-primary shop-item-button" type="button">
                  ADD TO CART
                </button>
              </div>
            </div>
            <div className="shop-item">
              <span className="shop-item-title">Arc Fault</span>
              <img
                className="shop-item-image"
                src="./images/323754964_3520606258261329_1219366652359417987_n.gif"
              />
              <div className="shop-item-details">
                <span className="shop-item-price">Private</span>
                <button className="btn btn-primary shop-item-button" type="button">
                  ADD TO CART
                </button>
              </div>
            </div>
            <div className="shop-item">
              <span className="shop-item-title">Crawl</span>
              <img
                className="shop-item-image"
                src="./images/322821776_568527955123801_921816956617425897_n%20(1).jpg"
              />
              <div className="shop-item-details">
                <span className="shop-item-price">Private</span>
                <button className="btn btn-primary shop-item-button" type="button">
                  ADD TO CART
                </button>
              </div>
            </div>
          </div>
          <h2 className="section-header">Sycotic Society ArtWork </h2>
          <hr />
          <div className="shop-items">
            <div className="shop-item">
              <span className="shop-item-title">Sycotic BTFD</span>
              <img
                className="shop-item-image"
                src="./images/322664106_1123565338304771_2425235359929313389_n%20(1).jpg"
              />
              <div className="shop-item-details">
                <span className="shop-item-price">Private</span>
                <button className="btn btn-primary shop-item-button" type="button">
                  ADD TO CART
                </button>
              </div>
            </div>
            <div className="shop-item">
              <span className="shop-item-title">Wired PUNK</span>
              <img
                className="shop-item-image"
                src="./images/323577071_896529951787689_7212182617120649949_n%20(1).jpg"
              />
              <div className="shop-item-details">
                <span className="shop-item-price">Private</span>
                <button className="btn btn-primary shop-item-button" type="button">
                  ADD TO CART
                </button>
              </div>
            </div>
            <div className="shop-item">
              <span className="shop-item-title">Dabb'in</span>
              <img
                className="shop-item-image"
                src="./images/323071297_1097916204210251_1786486724366281471_n%20(1).jpg"
              />
              <div className="shop-item-details">
                <span className="shop-item-price">Private</span>
                <button className="btn btn-primary shop-item-button" type="button">
                  ADD TO CART
                </button>
              </div>
            </div>
            <div className="shop-item">
              <span className="shop-item-title">Mind F#%k</span>
              <img
                className="shop-item-image"
                src="./images/322663901_941335210578424_1652339172632009618_n%20(1).jpg"
              />
              <div className="shop-item-details">
                <span className="shop-item-price">Private</span>
                <button className="btn btn-primary shop-item-button" type="button">
                  ADD TO CART
                </button>
              </div>
            </div>
          </div>
          <h2 className="section-header">
            Underrated Artist: Rebel PUNK + Wet Women
          </h2>
          <hr />

          <div className="shop-items">
            <div className="shop-item">
              <span className="shop-item-title">Delorean EX</span>
              <img
                className="shop-item-image"
                src="./images/322354250_554112660066328_6876708721695138728_n%20(1).jpg"
              />
              <div className="shop-item-details">
                <span className="shop-item-price">Privaye</span>
                <button className="btn btn-primary shop-item-button" type="button">
                  ADD TO CART
                </button>
              </div>
            </div>
            <div className="shop-item">
              <span className="shop-item-title">Rebel PUNK</span>
              <img
                className="shop-item-image"
                src="./images/323357197_864249411490286_4970945560639000489_n%20(1).jpg"
              />
              <div className="shop-item-details">
                <span className="shop-item-price">Private</span>
                <button className="btn btn-primary shop-item-button" type="button">
                  ADD TO CART
                </button>
              </div>
            </div>
            <div className="shop-item">
              <span className="shop-item-title">Empathetic</span>
              <img
                className="shop-item-image"
                src="./images/323536795_1330955767741295_9055596907241560739_n%20(1).jpg"
              />
              <div className="shop-item-details">
                <span className="shop-item-price">49.95</span>
                <button className="btn btn-primary shop-item-button" type="button">
                  ADD TO CART
                </button>
              </div>
            </div>
            <div className="shop-item">
              <span className="shop-item-title">Azura Inferno</span>
              <img
                className="shop-item-image"
                src="./images/322661639_1790625901318465_5312494453912311742_n%20(1).jpg"
              />
              <div className="shop-item-details">
                <span className="shop-item-price">49.95</span>
                <button className="btn btn-primary shop-item-button" type="button">
                  ADD TO CART
                </button>
              </div>
            </div>
          </div>
        </section>

        <section className="container content-section">
          <h2 className="section-header"></h2>
          <div className="shop-items">
            <div className="shop-item">
              <span className="shop-item-title"></span>

              <div className="shop-item-details">
                <span className="shop-item-price"></span>
              </div>
            </div>
            <div className="shop-item">
              <span className="shop-item-title"></span>

              <div className="shop-item-details">
                <span className="shop-item-price"></span>
              </div>
            </div>
          </div>
        </section>
        <section className="container content-section">
          <hr />
          <iframe
            src="https://gateway.ipfscdn.io/ipfs/QmbqEq5EQLx1aPurZFreM246fsKeawfpKDT8uzguAHAikr/marketplace.html?contract=0x7266BA8cA064fbFC96DAE22B5C29a468D178C253&chainId=137&listingId=0&theme=dark"
            width="500px"
            height="500px"
            style={{maxWidth:'100%'}}
            frameborder="0"
          ></iframe>
          <hr />
          <h2 className="section-header">SHOPPING CART</h2>
          <div className="cart-row">
            <span className="cart-item cart-header cart-column">ITEM</span>
            <span className="cart-price cart-header cart-column">PRICE</span>
            <span className="cart-quantity cart-header cart-column">QUANTITY</span>
          </div>
          <div className="cart-items"></div>
          <div className="cart-total">
            <strong className="cart-total-title">Total</strong>
            <span className="cart-total-price">$0</span>
          </div>

          <button id="connectButton" className="btn-primary">
            META MASK
          </button>
          <hr />
        </section>
        <Footer/>
    </div> 
  );
}
